name: Build and Test TCP Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential wget

    - name: Install libev from source
      run: |
        wget http://dist.schmorp.de/libev/Attic/libev-4.33.tar.gz
        tar -xzf libev-4.33.tar.gz
        cd libev-4.33
        ./configure
        make
        sudo make install

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run basic test
      run: |
        cd build
        ./server &  # Запуск сервера в фоновом режиме
        SERVER_PID=$!  # Сохранение PID запущенного процесса
        sleep 2  # Ожидание запуска сервера
        echo "Test message" | nc localhost 5000  # Отправка сообщения на сервер
        kill $SERVER_PID  # Завершение процесса сервера
