name: Build and Test TCP Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential wget

    - name: Install libev from source
      run: |
        wget http://dist.schmorp.de/libev/Attic/libev-4.33.tar.gz
        tar -xzf libev-4.33.tar.gz
        cd libev-4.33
        ./configure
        make
        sudo make install

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run basic test
      run: |
        cd build
        ./server &  # Start the server in the background
        SERVER_PID=$!  # Save the PID of the server process
        sleep 2  # Wait for the server to start
        echo "Sending test message to server"
        echo "Test message" | nc localhost 5000  # Send a test message to the server
        echo "Stopping server with PID $SERVER_PID"
        kill $SERVER_PID  # Stop the server process
        sleep 1  # Small delay to ensure the process stops
        if ps -p $SERVER_PID > /dev/null; then
          echo "Server did not terminate. Forcing termination."
          kill -9 $SERVER_PID  # Force stop if the server did not terminate
        else
          echo "Server terminated successfully."
        fi
